// console.log(module.parent.filename+ "  调用了模块  ======")
console.log(module.filename)
require('babel-core/register')
require('babel-polyfill')
require('./server/index.js')
// require('./test/dec.js')
